# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNlJWn1lxa3BgDv-ku1P2J-WDSkwoUxv
"""

import streamlit as st
import os

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import UnstructuredHTMLLoader
from langchain_core.runnables import RunnablePassthrough
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma

st.set_page_config(
    page_title="Samsung Washing Machine Chatbot",
    page_icon="🧺",
    layout="wide"
)

st.title("🧺 Samsung Washing Machine Manual Chatbot")
st.write("Ask questions about your Samsung washing machine manual.")

# Read API key
api_key = st.secrets.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")

if not api_key:
    st.error("Please configure your OPENAI_API_KEY.")
    st.stop()


@st.cache_resource
def build_rag():

    loader = UnstructuredHTMLLoader(
        file_path="washing_machine_manual.html"
    )

    docs = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    splits = splitter.split_documents(docs)

    embeddings = OpenAIEmbeddings(
        model="text-embedding-3-small",
        api_key=api_key
    )

    vectorstore = Chroma.from_documents(
        documents=splits,
        embedding=embeddings
    )

    retriever = vectorstore.as_retriever()

    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0,
        api_key=api_key
    )

    prompt = ChatPromptTemplate.from_template("""
You are an assistant for question-answering tasks.

Use the retrieved context to answer the question.

If the answer is not present in the context, say:
"I don't know."

Keep your answer concise.

Question:
{question}

Context:
{context}

Answer:
""")

    rag_chain = (
        {
            "context": retriever,
            "question": RunnablePassthrough()
        }
        | prompt
        | llm
    )

    return rag_chain


chain = build_rag()

question = st.text_input(
    "Ask your question",
    placeholder="Example: What is the cycle for DRUM CLEAN?"
)

if st.button("Get Answer"):

    if question.strip():

        with st.spinner("Searching manual..."):

            answer = chain.invoke(question)

        st.success(answer.content)