# -*- coding: utf-8 -*-
"""day-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5xvrwiv2498i9yMS20VGI-4d_LWlHFa
"""

"""
Streamlit RAG Chatbot for Samsung Washing Machine Manual
----------------------------------------------------------
Upload a washing-machine manual (HTML file), then ask questions about it.
Uses LangChain + Chroma + OpenAI for Retrieval Augmented Generation.

Run with:
    streamlit run rag_chatbot_app.py
"""

import os
import tempfile

import streamlit as st
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import UnstructuredHTMLLoader
from langchain_core.runnables import RunnablePassthrough
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma

# ----------------------------------------------------------------------
# Page config
# ----------------------------------------------------------------------
st.set_page_config(
    page_title="Washing Machine Manual Chatbot",
    page_icon="🧺",
    layout="centered",
)

st.title("🧺 Samsung Washing Machine Manual Chatbot")
st.caption(
    "Upload a manual (HTML), ask a question, and get a context-aware answer "
    "powered by Retrieval Augmented Generation (RAG)."
)

# ----------------------------------------------------------------------
# Sidebar: API key + file upload + settings
# ----------------------------------------------------------------------
with st.sidebar:
    st.header("Setup")

    # Never hardcode API keys in source. Prefer st.secrets, fall back to
    # a password-masked text input so the key is never persisted or shown.
    api_key = st.secrets.get("OPENAI_API_KEY", None) if hasattr(st, "secrets") else None
    if not api_key:
        api_key = st.text_input("OpenAI API Key", type="password")

    uploaded_file = st.file_uploader(
        "Upload manual (.html)", type=["html", "htm"]
    )

    chunk_size = st.slider("Chunk size", 500, 2000, 1000, step=100)
    chunk_overlap = st.slider("Chunk overlap", 0, 500, 200, step=50)
    temperature = st.slider("Model temperature", 0.0, 1.0, 0.0, step=0.1)

    build_clicked = st.button("Build knowledge base", type="primary")

# ----------------------------------------------------------------------
# Session state
# ----------------------------------------------------------------------
if "rag_chain" not in st.session_state:
    st.session_state.rag_chain = None
if "messages" not in st.session_state:
    st.session_state.messages = []

# ----------------------------------------------------------------------
# Build the RAG pipeline
# ----------------------------------------------------------------------
def build_rag_chain(html_path: str, api_key: str, chunk_size: int, chunk_overlap: int, temperature: float):
    os.environ["OPENAI_API_KEY"] = api_key

    # Load the HTML document
    loader = UnstructuredHTMLLoader(file_path=html_path)
    machine_docs = loader.load()

    # Split into chunks
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size, chunk_overlap=chunk_overlap
    )
    splits = text_splitter.split_documents(machine_docs)

    # Embeddings + vector store
    embeddings = OpenAIEmbeddings(model="text-embedding-3-small", openai_api_key=api_key)
    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)
    retriever = vectorstore.as_retriever()

    # LLM
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=temperature, api_key=api_key)

    # Prompt
    prompt = ChatPromptTemplate.from_template(
        """You are an assistant for question-answering tasks.
Use the following pieces of retrieved context to answer the question.
If you don't know the answer, just say that you don't know.
Use three sentences maximum and keep the answer concise.
Question: {question}
Context: {context}
Answer:"""
    )

    # Chain
    rag_chain = (
        {"context": retriever, "question": RunnablePassthrough()}
        | prompt
        | llm
    )
    return rag_chain


if build_clicked:
    if not api_key:
        st.sidebar.error("Please provide your OpenAI API key.")
    elif not uploaded_file:
        st.sidebar.error("Please upload an HTML manual file.")
    else:
        with st.spinner("Reading manual, chunking text, and building the vector store..."):
            try:
                # Save uploaded file to a temp path so UnstructuredHTMLLoader can read it
                with tempfile.NamedTemporaryFile(
                    delete=False, suffix=".html"
                ) as tmp_file:
                    tmp_file.write(uploaded_file.getvalue())
                    tmp_path = tmp_file.name

                st.session_state.rag_chain = build_rag_chain(
                    tmp_path, api_key, chunk_size, chunk_overlap, temperature
                )
                st.session_state.messages = []
                st.sidebar.success("Knowledge base ready! Ask a question below.")
            except Exception as e:
                st.sidebar.error(f"Error building knowledge base: {e}")

# ----------------------------------------------------------------------
# Chat interface
# ----------------------------------------------------------------------
st.divider()

if st.session_state.rag_chain is None:
    st.info("Upload a manual and click **Build knowledge base** in the sidebar to get started.")
else:
    # Show chat history
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    # Chat input
    query = st.chat_input("Ask a question about the manual, e.g. 'What is the cycle for DRUM CLEAN?'")

    if query:
        st.session_state.messages.append({"role": "user", "content": query})
        with st.chat_message("user"):
            st.write(query)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                try:
                    answer = st.session_state.rag_chain.invoke(query).content
                    st.write(answer)
                    st.session_state.messages.append({"role": "assistant", "content": answer})
                except Exception as e:
                    error_msg = f"Error generating answer: {e}"
                    st.error(error_msg)
                    st.session_state.messages.append({"role": "assistant", "content": error_msg})
